### ISSUE TITLE
License violations

### ISSUE THREAD

**Issue by MerijnHendriks** [kobrakon/SPO_DEV#2]
Hi! GabeOver and I (Senko-san on discord) sat down previously discussing the license violations of the source you uploaded here. He either is working on it or fixed it already. Can you please update the source to the correct version?

The license violation in particular is `CC BY-NC-SA`, which requires proper attribution to the author, which is nowhere to be found in the source. The author of the mods containing the license in question is `Alex`. 

Mods in question:
https://hub.sp-tarkov.com/files/file/375-alex-aio/
https://hub.sp-tarkov.com/files/file/344-better-lights-lasers/

**Comment by kobrakon** [comment]
Alex is attributed along with his works used in the "read me I MEAN IT! READ ME!.txt" in the credits section
